version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/readyz" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    ports:
      - "8080:8080"
